trigger:
  branches:
    include:
      - master
      - develop
      - homolog

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: application
    type: string
    default: "<APPLICATION NAME>"
  - name: description
    type: string
    default: "<DESCRIPTION>"
  - name: servicename
    type: string
    default: "<ECS SERVICE NAME>"

resources:
  repositories:
    - repository: templateRepo
      type: git
      name: GEcommerce/PipelineTemplates
      ref: refs/heads/master

stages:
  - template: ecs/setup-template.yml@templateRepo
    parameters:
      application: ${{ parameters.application }}

  - template: ecs/build-template.yml@templateRepo
    parameters:
      description: ${{ parameters.description }}
      application: ${{ parameters.application }}

  - template: ecs/publish-to-ecr-template.yml@templateRepo
    parameters:
      description: ${{ parameters.description }}
      application: ${{ parameters.application }}

  - template: ecs/deploy-template.yml@templateRepo
    parameters:
      description: ${{ parameters.description }}
      servicename: ${{ parameters.servicename}}
